# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# For Development, used below header for API Auth
# for name: user and password: secrets
# Authorization: Basic dXNlcjpzZWNyZXRz

development:
  api_auth_username: user
  api_auth_password: secrets
  send_user_auth_email: false
  sms_username: <%= ENV["SMS_USERNAME"] %>
  sms_password: <%= ENV["SMS_PASSWORD"] %>
  sms_senderid: <%= ENV["SMS_SENDER_ID"] %>
  secret_key_base: 4330877f005ac31318c1634fe02e8d6efadb55d05468c1bba14691d151b298b429730dbaf5394fa1ac13b6d389b4f73ae358ac3e283699a6a621b3ba9b26ba7b

test:
  secret_key_base: d7f2ff73171113d344f14c78a6359c2a2133ed1cdf66e87bea5ae667d885521447ac04f5a9f8aec0bfceca54f091a3423c249484bc527c0306646e53364add82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  sms_username: <%= ENV["SMS_USERNAME"] %>
  sms_password: <%= ENV["SMS_PASSWORD"] %>
  sms_senderid: <%= ENV["SMS_SENDER_ID"] %>
  api_auth_username: <%= ENV["API_AUTH_USERNAME"] %>
  api_auth_password: <%= ENV["API_AUTH_PASSWORD"] %>
  send_auth_emails:  <%= ENV["SEND_AUTH_EMAILS"] %>
  domain_name:       <%= ENV["DOMAIN_NAME"] %>
  secret_key_base:   <%= ENV["SECRET_KEY_BASE"] %>
  socket_request_origin: <%= ENV["SOCKET_REQUEST_ORIGIN"] %>
